name: Deploy to EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no -i <path-to-your-local-ssh-key> ${USER}@${HOST} << EOF
            # Debug: Check the OS
            cat /etc/os-release

            # Update package manager (for Amazon Linux)
            sudo yum update -y

            # Install PHP 7.4 and required extensions (for Amazon Linux 2)
            sudo amazon-linux-extras enable php7.4
            sudo yum install -y php php-cli php-mbstring php-xml php-mysqlnd php-zip unzip

            # Verify PHP version
            php -v

            # Install Composer
            if ! command -v composer &> /dev/null; then
              php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
              php composer-setup.php --install-dir=/usr/local/bin --filename=composer
              php -r "unlink('composer-setup.php');"
            fi

            # Verify Composer version
            composer --version

            mkdir -p /var/www && sudo chown ${USER}:${USER} /var/www
            cd /var/www

            # Clean existing directory safely
            sudo chown -R ${USER}:${USER} my-laravel-app || true
            rm -rf my-laravel-app

            # Debug: Check if GITHUB_TOKEN is set
            if [ -z "$GITHUB_TOKEN" ]; then
              echo "GITHUB_TOKEN is not set"
              exit 1
            fi

            # Clone the repository via HTTPS
            git clone https://github.com/nycacsoft-jaga/laravel-app.git my-laravel-app
            if [ ! -d "my-laravel-app" ]; then
              echo "Failed to clone repository"
              exit 1
            fi
            cd my-laravel-app

            # Verify composer.json exists
            if [ ! -f "composer.json" ]; then
              echo "composer.json not found in my-laravel-app"
              exit 1
            fi

            # Clear Composer cache and run composer install with verbose output
            composer clear-cache
            composer install --no-dev --optimize-autoloader -vvv

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            sudo chown -R ${USER}:${USER} /var/www/my-laravel-app
            chmod -R 755 /var/www/my-laravel-app/storage
          EOF