name: Deploy to EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
            mkdir -p /var/www && sudo chown ${USER}:${USER} /var/www
            cd /var/www

            # Clean existing directory safely
            sudo chown -R ${USER}:${USER} my-laravel-app || true
            rm -rf my-laravel-app

            # Clone via SSH (requires SSH key on EC2 and added to GitHub)
            git clone git@github.com:nycacsoft-jaga/laravel-app.git my-laravel-app
            cd my-laravel-app

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            sudo chown -R ${USER}:${USER} /var/www/my-laravel-app
            chmod -R 755 /var/www/my-laravel-app/storage
          EOF
