name: Deploy to EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
        run: |
          # Write the SSH private key to a file on the GitHub Actions runner
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          # Use the private_key file to SSH into the EC2 instance
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
            # Debug: Check the OS
            cat /etc/os-release

            # Write the private key for GitHub cloning to a file on the EC2 instance
            echo "$PRIVATE_KEY" > ~/.ssh/private_key && chmod 600 ~/.ssh/private_key

            # Update package manager (for Amazon Linux)
            sudo yum update -y

            # Install PHP 7.4 and required extensions (for Amazon Linux 2)
            sudo amazon-linux-extras enable php7.4
            sudo yum install -y php php-cli php-mbstring php-xml php-mysqlnd php-zip unzip

            # Verify PHP version
            php -v

            # Install Composer
            if ! command -v composer &> /dev/null; then
              php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
              php composer-setup.php --install-dir=/usr/local/bin --filename=composer
              php -r "unlink('composer-setup.php');"
            fi

            # Verify Composer version
            composer --version

            mkdir -p /var/www && sudo chown ${USER}:${USER} /var/www
            cd /var/www

            # Clean existing directory safely
            sudo chown -R ${USER}:${USER} my-laravel-app || true
            rm -rf my-laravel-app

            # Clone the repository with host key verification disabled
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key" git clone https://github.com/nycasoft-jaga/laravel-app.git my-laravel-app
            if [ ! -d "my-laravel-app" ]; then
              echo "Failed to clone repository"
              exit 1
            fi
            cd my-laravel-app

            # Verify composer.json exists
            if [ ! -f "composer.json" ]; then
              echo "composer.json not found in my-laravel-app"
              exit 1
            fi

            # Clear Composer cache and run composer install with verbose output
            composer clear-cache
            composer install --no-dev --optimize-autoloader -vvv

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            sudo chown -R ${USER}:${USER} /var/www/my-laravel-app
            chmod -R 755 /var/www/my-laravel-app/storage

            # Clean up the private key on the EC2 instance
            rm ~/.ssh/private_key
          EOF

          # Clean up the private key on the GitHub Actions runner
          rm private_key