name: Deploy to EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
        run: |
          # Save the private key to a file and set permissions
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
            # Add the ondrej/php PPA to get newer PHP versions
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt-get update

            # Install PHP 7.4 and required extensions
            sudo apt-get install -y php7.4 php7.4-cli php7.4-mbstring php7.4-xml php7.4-mysql php7.4-zip unzip

            # Set PHP 7.4 as the default version
            sudo update-alternatives --set php /usr/bin/php7.4
            sudo update-alternatives --set phpize /usr/bin/phpize7.4
            sudo update-alternatives --set php-config /usr/bin/php-config7.4

            # Disable older PHP versions (e.g., PHP 7.0) to avoid conflicts
            sudo apt-get remove -y php7.0 php7.0-cli php7.0-mbstring php7.0-xml php7.0-mysql php7.0-zip --purge || true

            # Verify PHP version
            php -v

            # Install Composer
            if ! command -v composer &> /dev/null; then
              php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
              php composer-setup.php --install-dir=/usr/local/bin --filename=composer
              php -r "unlink('composer-setup.php');"
            fi

            # Verify Composer version
            composer --version

            mkdir -p /var/www && sudo chown ${USER}:${USER} /var/www
            cd /var/www

            # Clean existing directory safely
            sudo chown -R ${USER}:${USER} my-laravel-app || true
            rm -rf my-laravel-app

            # Debug: Test SSH connection to GitHub
            ssh -o StrictHostKeyChecking=no -i private_key git@github.com || echo "SSH connection to GitHub failed"

            # Clone the repository with host key verification disabled
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i private_key" git clone git@github.com:nycacsoft-jaga/laravel-app.git my-laravel-app
            if [ ! -d "my-laravel-app" ]; then
              echo "Failed to clone repository"
              exit 1
            fi
            cd my-laravel-app

            # Verify composer.json exists
            if [ ! -f "composer.json" ]; then
              echo "composer.json not found in my-laravel-app"
              exit 1
            fi

            # Clear Composer cache and run composer install with verbose output
            composer clear-cache
            composer install --no-dev --optimize-autoloader -vvv

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            sudo chown -R ${USER}:${USER} /var/www/my-laravel-app
            chmod -R 755 /var/www/my-laravel-app/storage
          EOF
          rm private_key